### ISSUE TITLE
[SUGGESTION] Make use of npx

### ISSUE THREAD

**Issue by glc-mvion** [jez/git-heatmap#5]
npx is a cli tool from Node.js team that enable running npm package without installing them system-wide.

npx can be installed via npm : `npm i -g npx`

As some recommends not storing any global package apart package managers, this is a possible alternative that having to install the bars package globally.

If you're ok with that, I'll be happy to do a pull request !

**Comment by jez** [comment]
I'd sooner do something like

```bash
npm install --save bars

# ... in the code ...
/usr/local/path/to/git-heatmap/node_modules/.bin/bars
```

Because if we pull in `npx` now we have two JavaScript dependencies instead of just one. But as soon as we have a package.json, then that means we need a post-install script that runs `npm install`, ... etc.

I prefer to just be able to stick the script file in a `bin/` folder somewhere and rely on the `bars` command globally. If this becomes an issue, (say, there's lots of rapid development and breaking changes to the `bars` command), we can move it to a local dependency.

IMO, that's premature optimization.

Thanks for the suggestion though! Hope `git-heatmap` can still be of use to you.
